In [41]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier


df = pd.read_csv("/content/new_dataset.csv", delimiter=',')
df.info
print(list(df.columns))

['Q1A', 'Q2A', 'Q3A', 'Q4A', 'Q5A', 'Q6A', 'Q7A', 'Q8A', 'Q9A', 'Q10A', 'Q11A', 'Q12A', 'Q13A', 'Q14A', 'Q15A', 'Q16A', 'Q17A', 'Q18A', 'Q19A', 'Q20A', 'Q21A', 'Q22A', 'Q23A', 'Q24A', 'Q25A', 'Q26A', 'Q27A', 'Q28A', 'Q29A', 'Q30A', 'Q31A', 'Q32A', 'Q33A', 'Q34A', 'Q35A', 'Q36A', 'Q37A', 'Q38A', 'Q39A', 'Q40A', 'Q41A', 'Q42A', 'education', 'gender', 'age', 'married', 'familysize', 'Stress', 'Anxiety', 'Depression']

In [42]:
df.head()

,Q1A,Q2A,Q3A,Q4A,Q5A,Q6A,Q7A,Q8A,Q9A,Q10A,...,Q41A,Q42A,education,gender,age,married,familysize,Stress,Anxiety,Depression
0,3,3,1,3,3,3,3,3,1,0,...,3,3,2,2,16,1,2,Sangat Parah,Sangat Parah,Parah
1,3,0,1,2,3,3,2,3,2,1,...,1,1,2,2,16,1,4,Parah,Parah,Parah
2,2,0,3,0,3,2,0,2,1,3,...,0,3,2,2,17,1,3,Ringan,Sedang,Sangat Parah
3,1,2,1,0,2,2,3,1,2,2,...,3,1,1,2,13,1,5,Ringan,Parah,Sedang
4,1,1,2,3,3,1,3,3,3,2,...,3,2,3,2,19,1,4,Parah,Sangat Parah,Sangat Parah

## Depression, Stress, Anxiety Split Set

In [46]:
Depression = df[['Q3A', 'Q5A', 'Q10A', 'Q13A', 'Q16A', 'Q17A', 'Q21A', 'Q24A', 'Q26A',
       'Q31A', 'Q34A', 'Q37A', 'Q38A', 'Q42A', 'education', 'gender', 'age', 'married', 'familysize', 'Depression']]
X_De = Depression.iloc[:, :19]
Y_De = Depression.iloc[:, 19:]

Stress = df[['Q1A', 'Q6A', 'Q8A', 'Q11A', 'Q12A', 'Q14A', 'Q18A', 'Q22A', 'Q27A',
       'Q29A', 'Q32A', 'Q33A', 'Q35A', 'Q39A', 'education', 'gender', 'age', 'married', 'familysize', 'Anxiety']]
X_St = Stress.iloc[:, :19]
Y_St = Stress.iloc[:, 19:]

Anxiety = df[['Q2A', 'Q4A', 'Q7A', 'Q9A', 'Q15A', 'Q19A', 'Q20A', 'Q23A', 'Q25A',
       'Q28A', 'Q30A', 'Q36A', 'Q40A', 'Q41A', 'education', 'gender', 'age', 'married', 'familysize', 'Stress']]
X_An = Anxiety.iloc[:, :19]
Y_An = Anxiety.iloc[:, 19:]

# Depression Training & Test Set

In [47]:
de_train_features, de_test_features, de_train_labels, de_test_labels = train_test_split(X_De, Y_De, test_size=0.2, random_state=50)
print(de_train_features.shape)
print(de_test_features.shape)
print(de_train_labels.shape)
print(de_test_labels.shape)

(31779, 19)
(7945, 19)
(31779, 1)
(7945, 1)

# Stress Training & Test Set

In [48]:
st_train_features, st_test_features, st_train_labels, st_test_labels = train_test_split(X_St, Y_St, test_size=0.2, random_state=50)
print(st_train_features.shape)
print(st_test_features.shape)
print(st_train_labels.shape)
print(st_test_labels.shape)

(31779, 19)
(7945, 19)
(31779, 1)
(7945, 1)

# Anxiety Training & Test Set

In [49]:
de_train_features, de_test_features, de_train_labels, de_test_labels = train_test_split(X_De, Y_De, test_size=0.2, random_state=50)
print(st_train_features.shape)
print(st_test_features.shape)
print(st_train_labels.shape)
print(st_test_labels.shape)

(31779, 19)
(7945, 19)
(31779, 1)
(7945, 1)